name: 'Nomad Cli'
description: 'nomad cli for run varius commands'
inputs:
  token:
    description: 'Token used to authenticate with a nomad server'
    required: true
  address:
    description: 'Address of the nomad server'
    required: true
  nomad_cli_args:
    description: 'Args for nomad-cli'
    required: true
    default: 'nomad'
runs:
  using: 'docker'
  image: 'docker://hendrikmaus/nomad-cli:1.2.3'
  env:
    NOMAD_TOKEN: ${{ inputs.token }}
    NOMAD_ADDR: ${{ inputs.address }}
  entrypoint: 'nomad'
  args:
    - ${{ inputs.nomad_cli_args }}

branding:
  icon: 'upload-cloud'
  color: 'green'
